//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refugio.App_Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Refugio.App_Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error deleting register.
        /// </summary>
        internal static string ErrorDeletingRegister {
            get {
                return ResourceManager.GetString("ErrorDeletingRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error displaying details.
        /// </summary>
        internal static string ErrorDisplayingDetails {
            get {
                return ResourceManager.GetString("ErrorDisplayingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The register in the database cannot be updated.
        /// </summary>
        internal static string ErrorProcesingUpdate {
            get {
                return ResourceManager.GetString("ErrorProcesingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error processing edit.
        /// </summary>
        internal static string ErrorProcessingEdit {
            get {
                return ResourceManager.GetString("ErrorProcessingEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error processing listing.
        /// </summary>
        internal static string ErrorProcessingListing {
            get {
                return ResourceManager.GetString("ErrorProcessingListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error occurred while saving.
        /// </summary>
        internal static string ErrorProcessingSave {
            get {
                return ResourceManager.GetString("ErrorProcessingSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No identifier has been provided.
        /// </summary>
        internal static string IdNotProvided {
            get {
                return ResourceManager.GetString("IdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record deleted successfully.
        /// </summary>
        internal static string SuccessDataDelete {
            get {
                return ResourceManager.GetString("SuccessDataDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data has been saved successfully.
        /// </summary>
        internal static string SuccessDataSave {
            get {
                return ResourceManager.GetString("SuccessDataSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There were modifications while you were performing the operation. Please reload the page and try again.
        /// </summary>
        internal static string ThereWereModifications {
            get {
                return ResourceManager.GetString("ThereWereModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In case of persistent errors, please try again or contact support.
        /// </summary>
        internal static string TryAgainContactSupport {
            get {
                return ResourceManager.GetString("TryAgainContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Veterinarian.
        /// </summary>
        internal static string Veterinarian {
            get {
                return ResourceManager.GetString("Veterinarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No veterinarian found with this identifier.
        /// </summary>
        internal static string VeterinarianNotFoundById {
            get {
                return ResourceManager.GetString("VeterinarianNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Veterinarians.
        /// </summary>
        internal static string Veterinarians {
            get {
                return ResourceManager.GetString("Veterinarians", resourceCulture);
            }
        }
    }
}
