//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refugio.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Refugio.Resources.Languages.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apartment number.
        /// </summary>
        public static string ApartmentNumber {
            get {
                return ResourceManager.GetString("ApartmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear filters.
        /// </summary>
        public static string ClearFilters {
            get {
                return ResourceManager.GetString("ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultation fee.
        /// </summary>
        public static string ConsultationFee {
            get {
                return ResourceManager.GetString("ConsultationFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error deleting register.
        /// </summary>
        public static string ErrorDeletingRegister {
            get {
                return ResourceManager.GetString("ErrorDeletingRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error displaying details.
        /// </summary>
        public static string ErrorDisplayingDetails {
            get {
                return ResourceManager.GetString("ErrorDisplayingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The register in the database cannot be updated.
        /// </summary>
        public static string ErrorProcesingUpdate {
            get {
                return ResourceManager.GetString("ErrorProcesingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error processing edit.
        /// </summary>
        public static string ErrorProcessingEdit {
            get {
                return ResourceManager.GetString("ErrorProcessingEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error processing listing.
        /// </summary>
        public static string ErrorProcessingListing {
            get {
                return ResourceManager.GetString("ErrorProcessingListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error occurred while saving.
        /// </summary>
        public static string ErrorProcessingSave {
            get {
                return ResourceManager.GetString("ErrorProcessingSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field must be between 0 and 9999999999999999.
        /// </summary>
        public static string FieldDecimalBetween {
            get {
                return ResourceManager.GetString("FieldDecimalBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No identifier has been provided.
        /// </summary>
        public static string IdNotProvided {
            get {
                return ResourceManager.GetString("IdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In landing.
        /// </summary>
        public static string InLanding {
            get {
                return ResourceManager.GetString("InLanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is permanent.
        /// </summary>
        public static string IsPermanent {
            get {
                return ResourceManager.GetString("IsPermanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field must be shorter than 10 characters.
        /// </summary>
        public static string MaxNumberOfCharacters10 {
            get {
                return ResourceManager.GetString("MaxNumberOfCharacters10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field must be shorter than 100 characters.
        /// </summary>
        public static string MaxNumberOfCharacters100 {
            get {
                return ResourceManager.GetString("MaxNumberOfCharacters100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field must be shorter than 15 characters.
        /// </summary>
        public static string MaxNumberOfCharacters15 {
            get {
                return ResourceManager.GetString("MaxNumberOfCharacters15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field must be shorter than 50 characters.
        /// </summary>
        public static string MaxNumberOfCharacters50 {
            get {
                return ResourceManager.GetString("MaxNumberOfCharacters50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field must be longer than 4 characters.
        /// </summary>
        public static string MinNumberOfCharacters4 {
            get {
                return ResourceManager.GetString("MinNumberOfCharacters4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Select --.
        /// </summary>
        public static string OptionSelect {
            get {
                return ResourceManager.GetString("OptionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aditional phone number.
        /// </summary>
        public static string PhoneNomberAditional {
            get {
                return ResourceManager.GetString("PhoneNomberAditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main phone number.
        /// </summary>
        public static string PhoneNumberMain {
            get {
                return ResourceManager.GetString("PhoneNumberMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Professional license.
        /// </summary>
        public static string ProfessionalLicense {
            get {
                return ResourceManager.GetString("ProfessionalLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Professionals.
        /// </summary>
        public static string Professionals {
            get {
                return ResourceManager.GetString("Professionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field is required.
        /// </summary>
        public static string RequieredField {
            get {
                return ResourceManager.GetString("RequieredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Speciality.
        /// </summary>
        public static string Speciality {
            get {
                return ResourceManager.GetString("Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Street address.
        /// </summary>
        public static string StreetAddress {
            get {
                return ResourceManager.GetString("StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record deleted successfully.
        /// </summary>
        public static string SuccessDataDelete {
            get {
                return ResourceManager.GetString("SuccessDataDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data has been saved successfully.
        /// </summary>
        public static string SuccessDataSave {
            get {
                return ResourceManager.GetString("SuccessDataSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to delete this.
        /// </summary>
        public static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There were modifications while you were performing the operation. Please reload the page and try again.
        /// </summary>
        public static string ThereWereModifications {
            get {
                return ResourceManager.GetString("ThereWereModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time slot.
        /// </summary>
        public static string TimeSlot {
            get {
                return ResourceManager.GetString("TimeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In case of persistent errors, please try again or contact support.
        /// </summary>
        public static string TryAgainContactSupport {
            get {
                return ResourceManager.GetString("TryAgainContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Veterinarian.
        /// </summary>
        public static string Veterinarian {
            get {
                return ResourceManager.GetString("Veterinarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No veterinarian found with this identifier.
        /// </summary>
        public static string VeterinarianNotFoundById {
            get {
                return ResourceManager.GetString("VeterinarianNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Veterinarians.
        /// </summary>
        public static string Veterinarians {
            get {
                return ResourceManager.GetString("Veterinarians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
