//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refugio.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RefugioEntities : DbContext
    {
        public RefugioEntities()
            : base("name=RefugioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Staff> Staff { get; set; }
        public DbSet<TimeSlotRange> TimeSlotRange { get; set; }
        public DbSet<Veterinarian> Veterinarian { get; set; }
        public DbSet<VeterinarianSpeciality> VeterinarianSpeciality { get; set; }
        public DbSet<vw_VeterinarianSpecialities> vw_VeterinarianSpecialities { get; set; }
    }
}
