//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refugio.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSlotRange
    {
        public TimeSlotRange()
        {
            this.Veterinarian = new HashSet<Veterinarian>();
        }
    
        public int Id { get; set; }
        public string TimeRange { get; set; }
    
        public virtual ICollection<Veterinarian> Veterinarian { get; set; }
    }
}
