//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refugio.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veterinarian
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StreetAddress { get; set; }
        public string ApartmentNumber { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string PhoneNumberMain { get; set; }
        public string PhoneNumberAditional { get; set; }
        public int Speciality { get; set; }
        public bool IsPermanent { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> TimeSlot { get; set; }
        public string ProfessionalLicense { get; set; }
        public string ForDescription { get; set; }
        public string State { get; set; }
    
        public virtual VeterinarianSpeciality VeterinarianSpeciality { get; set; }
        public virtual TimeSlotRange TimeSlotRange { get; set; }
    }
}
